name: Validate Composer

on:
  workflow_call:
    inputs:
      php-version:
        default: 8.0
        required: false

jobs:
  composer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: {{ inputs.php-version }}
          coverage: none
          tools: composer:v2

      - name: Run composer validate
        run: composer validate --no-check-all --strict
