name: Deploy

on:
  workflow_call:
    inputs:
      php-version:
        required: false
        type: string
        default: 8.0
      deployer-version:
        required: false
        type: string
        default: v6.8.0
    secrets:
      PRIVATE_KEY:
        required: true
      KNOWN_HOSTS:
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-rc:
    name: RC
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'

    environment: rc

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP and Deployer
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ inputs.php-version }}
          coverage: none
          tools: deployer:${{ inputs.deployer-version }}

      - name: Setup SSH connection
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact-build

      - name: Add known hosts
        run: echo '${{ secrets.KNOWN_HOSTS }}' >> ~/.ssh/known_hosts

      - name: Deploy to RC
        run: deployer deploy rc -vvv

      - name: Delete artifact
        if: always()
        uses: geekyeggo/delete-artifact@v1
        with:
          name: artifact-build

  deploy-prod:
    name: Production
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    environment: prod

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP and Deployer
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ inputs.php-version }}
          coverage: none
          tools: deployer:${{ inputs.deployer-version }}

      - name: Setup SSH connection
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact-build

      - name: Add known hosts
        run: echo '${{ secrets.KNOWN_HOSTS }}' >> ~/.ssh/known_hosts

      - name: Deploy to production
        run: deployer deploy prod -vvv

      - name: Delete artifact
        if: always()
        uses: geekyeggo/delete-artifact@v1
        with:
          name: artifact-build
