name: Run PHPStan

on:
  workflow_call:
    inputs:
      php-version:
        required: false
        type: string
        default: 8.3
      config-file:
        required: false
        type: string
        default: phpstan.neon

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ inputs.php-version }}
          tools: composer:v2
          coverage: none

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Install composer dependencies
        run: composer install -n --prefer-dist

      - name: Execute type checking
        run: vendor/bin/phpstan --configuration=${{ inputs.config-file }}
