name: Run PHPStan

on:
  workflow_call:
    inputs:
      php-version:
        required: false
        type: string
        default: 8.3

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ inputs.php-version }}
          coverage: none
          tools: composer:v2
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Install composer dependencies
        run: composer install -n --prefer-dist

      - name: Run phpstan
        run: composer phpstan
