name: Run PHPStan

on:
  workflow_call:
    inputs:
      php-version:
        required: false
        type: string
        default: 8.1

jobs:
  composer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ inputs.php-version }}
          coverage: none
          tools: composer:v2

      - name: Run composer validate
        run: composer phpstan
