name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      php-version:
        required: false
        type: string
        default: 8.3
      deployer-version:
        required: false
        type: string
        default: v7.x
    secrets:
      PRIVATE_KEY:
        required: true
      KNOWN_HOSTS:
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest

    environment: ${{ inputs.environment }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP and Deployer
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ inputs.php-version }}
          coverage: none
          tools: deployer:${{ inputs.deployer-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}

      - name: Setup SSH connection
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact-build

      - name: Add known hosts
        run: echo '${{ secrets.KNOWN_HOSTS }}' >> ~/.ssh/known_hosts

      - name: Deploy to environment
        run: deployer deploy stage=${{ inputs.environment }} -vvv

      - name: Delete artifact
        if: always()
        uses: geekyeggo/delete-artifact@v5
        with:
          name: artifact-build
